// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePapers(arg1) {
  return window['go']['app']['App']['AnalyzePapers'](arg1);
}

export function ApplyPendingDatabaseRestore() {
  return window['go']['app']['App']['ApplyPendingDatabaseRestore']();
}

export function ApplyScreeningChoice(arg1, arg2) {
  return window['go']['app']['App']['ApplyScreeningChoice'](arg1, arg2);
}

export function AskDeepReadPaper(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AskDeepReadPaper'](arg1, arg2, arg3, arg4);
}

export function AttachLocalPDFToPaper(arg1, arg2) {
  return window['go']['app']['App']['AttachLocalPDFToPaper'](arg1, arg2);
}

export function CancelDeepReadAI() {
  return window['go']['app']['App']['CancelDeepReadAI']();
}

export function CancelDeepStartTask(arg1) {
  return window['go']['app']['App']['CancelDeepStartTask'](arg1);
}

export function CancelPendingDatabaseRestore() {
  return window['go']['app']['App']['CancelPendingDatabaseRestore']();
}

export function CancelScreening(arg1) {
  return window['go']['app']['App']['CancelScreening'](arg1);
}

export function CancelScreeningTask(arg1) {
  return window['go']['app']['App']['CancelScreeningTask'](arg1);
}

export function CompleteScreening(arg1, arg2) {
  return window['go']['app']['App']['CompleteScreening'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['app']['App']['CreateFolder'](arg1);
}

export function CreateFolderNode(arg1) {
  return window['go']['app']['App']['CreateFolderNode'](arg1);
}

export function CreateScreeningSession(arg1) {
  return window['go']['app']['App']['CreateScreeningSession'](arg1);
}

export function DeleteFolderNode(arg1) {
  return window['go']['app']['App']['DeleteFolderNode'](arg1);
}

export function DeletePaper(arg1) {
  return window['go']['app']['App']['DeletePaper'](arg1);
}

export function EnhancedSearchPapers(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['EnhancedSearchPapers'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExtractPaperContent(arg1) {
  return window['go']['app']['App']['ExtractPaperContent'](arg1);
}

export function GetDeepReadPDFBytes(arg1) {
  return window['go']['app']['App']['GetDeepReadPDFBytes'](arg1);
}

export function GetDeepReadPDFURL(arg1) {
  return window['go']['app']['App']['GetDeepReadPDFURL'](arg1);
}

export function GetDeepReadState(arg1) {
  return window['go']['app']['App']['GetDeepReadState'](arg1);
}

export function GetDeepStartSession(arg1) {
  return window['go']['app']['App']['GetDeepStartSession'](arg1);
}

export function GetExtractProgress(arg1) {
  return window['go']['app']['App']['GetExtractProgress'](arg1);
}

export function GetFolderStorageTreeOverview() {
  return window['go']['app']['App']['GetFolderStorageTreeOverview']();
}

export function GetFolderTree() {
  return window['go']['app']['App']['GetFolderTree']();
}

export function GetFolders() {
  return window['go']['app']['App']['GetFolders']();
}

export function GetInitialState() {
  return window['go']['app']['App']['GetInitialState']();
}

export function GetLLMUsage() {
  return window['go']['app']['App']['GetLLMUsage']();
}

export function GetLocalStorageOverview() {
  return window['go']['app']['App']['GetLocalStorageOverview']();
}

export function GetPDFServiceStatus() {
  return window['go']['app']['App']['GetPDFServiceStatus']();
}

export function GetPapers(arg1) {
  return window['go']['app']['App']['GetPapers'](arg1);
}

export function GetPendingDatabaseRestore() {
  return window['go']['app']['App']['GetPendingDatabaseRestore']();
}

export function GetScreeningSession(arg1) {
  return window['go']['app']['App']['GetScreeningSession'](arg1);
}

export function GetSecretPrefill() {
  return window['go']['app']['App']['GetSecretPrefill']();
}

export function GetSyncConflicts() {
  return window['go']['app']['App']['GetSyncConflicts']();
}

export function GetSyncPreview() {
  return window['go']['app']['App']['GetSyncPreview']();
}

export function GetSyncProgress() {
  return window['go']['app']['App']['GetSyncProgress']();
}

export function GetSyncRecords(arg1) {
  return window['go']['app']['App']['GetSyncRecords'](arg1);
}

export function GetSyncSettings() {
  return window['go']['app']['App']['GetSyncSettings']();
}

export function GetSyncStatus() {
  return window['go']['app']['App']['GetSyncStatus']();
}

export function GetTranslations(arg1) {
  return window['go']['app']['App']['GetTranslations'](arg1);
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ImportPapers(arg1, arg2) {
  return window['go']['app']['App']['ImportPapers'](arg1, arg2);
}

export function ImportPapersWithAssets(arg1, arg2) {
  return window['go']['app']['App']['ImportPapersWithAssets'](arg1, arg2);
}

export function ListDeepStartSessions() {
  return window['go']['app']['App']['ListDeepStartSessions']();
}

export function ListScreeningSessions() {
  return window['go']['app']['App']['ListScreeningSessions']();
}

export function MoveFolderNode(arg1) {
  return window['go']['app']['App']['MoveFolderNode'](arg1);
}

export function MovePaperToFolder(arg1, arg2) {
  return window['go']['app']['App']['MovePaperToFolder'](arg1, arg2);
}

export function MovePapersToFolder(arg1, arg2) {
  return window['go']['app']['App']['MovePapersToFolder'](arg1, arg2);
}

export function PrepareDeepReadPaper(arg1) {
  return window['go']['app']['App']['PrepareDeepReadPaper'](arg1);
}

export function RefreshBaiduToken() {
  return window['go']['app']['App']['RefreshBaiduToken']();
}

export function RenameFolderNode(arg1) {
  return window['go']['app']['App']['RenameFolderNode'](arg1);
}

export function ReplyDeepStartSession(arg1, arg2) {
  return window['go']['app']['App']['ReplyDeepStartSession'](arg1, arg2);
}

export function RerunDeepStartSearch(arg1, arg2) {
  return window['go']['app']['App']['RerunDeepStartSearch'](arg1, arg2);
}

export function ResolveSyncConflict(arg1, arg2) {
  return window['go']['app']['App']['ResolveSyncConflict'](arg1, arg2);
}

export function RetryFolderPendingDownloads(arg1) {
  return window['go']['app']['App']['RetryFolderPendingDownloads'](arg1);
}

export function RetryPaperDownload(arg1) {
  return window['go']['app']['App']['RetryPaperDownload'](arg1);
}

export function RetryPaperDownloadWithURL(arg1, arg2) {
  return window['go']['app']['App']['RetryPaperDownloadWithURL'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveDeepReadNote(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveDeepReadNote'](arg1, arg2, arg3);
}

export function SaveSyncSettings(arg1) {
  return window['go']['app']['App']['SaveSyncSettings'](arg1);
}

export function SearchPapers(arg1, arg2) {
  return window['go']['app']['App']['SearchPapers'](arg1, arg2);
}

export function SelectAndAttachPaperPDF(arg1) {
  return window['go']['app']['App']['SelectAndAttachPaperPDF'](arg1);
}

export function SelectScreeningPDFs() {
  return window['go']['app']['App']['SelectScreeningPDFs']();
}

export function StartDeepStartSession(arg1, arg2) {
  return window['go']['app']['App']['StartDeepStartSession'](arg1, arg2);
}

export function SupplementDeepStartSearch(arg1, arg2, arg3) {
  return window['go']['app']['App']['SupplementDeepStartSearch'](arg1, arg2, arg3);
}

export function TranslatePaperSection(arg1, arg2, arg3) {
  return window['go']['app']['App']['TranslatePaperSection'](arg1, arg2, arg3);
}

export function TriggerSync() {
  return window['go']['app']['App']['TriggerSync']();
}

export function UndoDeepStartNarrow(arg1) {
  return window['go']['app']['App']['UndoDeepStartNarrow'](arg1);
}

export function UpdateDeepStartSelections(arg1, arg2, arg3) {
  return window['go']['app']['App']['UpdateDeepStartSelections'](arg1, arg2, arg3);
}

export function UploadScreeningFiles(arg1, arg2) {
  return window['go']['app']['App']['UploadScreeningFiles'](arg1, arg2);
}
