// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzePapers(arg1) {
  return window['go']['main']['App']['AnalyzePapers'](arg1);
}

export function ApplyScreeningChoice(arg1, arg2) {
  return window['go']['main']['App']['ApplyScreeningChoice'](arg1, arg2);
}

export function AttachLocalPDFToPaper(arg1, arg2) {
  return window['go']['main']['App']['AttachLocalPDFToPaper'](arg1, arg2);
}

export function CancelDeepStartTask(arg1) {
  return window['go']['main']['App']['CancelDeepStartTask'](arg1);
}

export function CancelScreening(arg1) {
  return window['go']['main']['App']['CancelScreening'](arg1);
}

export function CompleteScreening(arg1, arg2) {
  return window['go']['main']['App']['CompleteScreening'](arg1, arg2);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateFolderNode(arg1) {
  return window['go']['main']['App']['CreateFolderNode'](arg1);
}

export function CreateScreeningSession(arg1) {
  return window['go']['main']['App']['CreateScreeningSession'](arg1);
}

export function DeleteFolderNode(arg1) {
  return window['go']['main']['App']['DeleteFolderNode'](arg1);
}

export function DeletePaper(arg1) {
  return window['go']['main']['App']['DeletePaper'](arg1);
}

export function EnhancedSearchPapers(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['EnhancedSearchPapers'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExtractPaperContent(arg1) {
  return window['go']['main']['App']['ExtractPaperContent'](arg1);
}

export function GetDeepReadPDFBytes(arg1) {
  return window['go']['main']['App']['GetDeepReadPDFBytes'](arg1);
}

export function GetDeepReadState(arg1) {
  return window['go']['main']['App']['GetDeepReadState'](arg1);
}

export function GetDeepStartSession(arg1) {
  return window['go']['main']['App']['GetDeepStartSession'](arg1);
}

export function GetExtractProgress(arg1) {
  return window['go']['main']['App']['GetExtractProgress'](arg1);
}

export function GetFolderStorageTreeOverview() {
  return window['go']['main']['App']['GetFolderStorageTreeOverview']();
}

export function GetFolderTree() {
  return window['go']['main']['App']['GetFolderTree']();
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function GetLocalStorageOverview() {
  return window['go']['main']['App']['GetLocalStorageOverview']();
}

export function GetPapers(arg1) {
  return window['go']['main']['App']['GetPapers'](arg1);
}

export function GetScreeningSession(arg1) {
  return window['go']['main']['App']['GetScreeningSession'](arg1);
}

export function GetSecretPrefill() {
  return window['go']['main']['App']['GetSecretPrefill']();
}

export function GetSyncConflicts() {
  return window['go']['main']['App']['GetSyncConflicts']();
}

export function GetSyncProgress() {
  return window['go']['main']['App']['GetSyncProgress']();
}

export function GetSyncRecords(arg1) {
  return window['go']['main']['App']['GetSyncRecords'](arg1);
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetTranslations(arg1) {
  return window['go']['main']['App']['GetTranslations'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportPapers(arg1, arg2) {
  return window['go']['main']['App']['ImportPapers'](arg1, arg2);
}

export function ImportPapersWithAssets(arg1, arg2) {
  return window['go']['main']['App']['ImportPapersWithAssets'](arg1, arg2);
}

export function ListDeepStartSessions() {
  return window['go']['main']['App']['ListDeepStartSessions']();
}

export function ListScreeningSessions() {
  return window['go']['main']['App']['ListScreeningSessions']();
}

export function PrepareDeepReadPaper(arg1) {
  return window['go']['main']['App']['PrepareDeepReadPaper'](arg1);
}

export function ReplyDeepStartSession(arg1, arg2) {
  return window['go']['main']['App']['ReplyDeepStartSession'](arg1, arg2);
}

export function RerunDeepStartSearch(arg1, arg2) {
  return window['go']['main']['App']['RerunDeepStartSearch'](arg1, arg2);
}

export function ResolveSyncConflict(arg1, arg2) {
  return window['go']['main']['App']['ResolveSyncConflict'](arg1, arg2);
}

export function RetryFolderPendingDownloads(arg1) {
  return window['go']['main']['App']['RetryFolderPendingDownloads'](arg1);
}

export function RetryPaperDownload(arg1) {
  return window['go']['main']['App']['RetryPaperDownload'](arg1);
}

export function RetryPaperDownloadWithURL(arg1, arg2) {
  return window['go']['main']['App']['RetryPaperDownloadWithURL'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveDeepReadNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDeepReadNote'](arg1, arg2, arg3);
}

export function SearchPapers(arg1, arg2) {
  return window['go']['main']['App']['SearchPapers'](arg1, arg2);
}

export function SelectAndAttachPaperPDF(arg1) {
  return window['go']['main']['App']['SelectAndAttachPaperPDF'](arg1);
}

export function SelectScreeningPDFs() {
  return window['go']['main']['App']['SelectScreeningPDFs']();
}

export function StartDeepStartSession(arg1, arg2) {
  return window['go']['main']['App']['StartDeepStartSession'](arg1, arg2);
}

export function SupplementDeepStartSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['SupplementDeepStartSearch'](arg1, arg2, arg3);
}

export function TranslatePaperSection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranslatePaperSection'](arg1, arg2, arg3);
}

export function TriggerSync() {
  return window['go']['main']['App']['TriggerSync']();
}

export function UndoDeepStartNarrow(arg1) {
  return window['go']['main']['App']['UndoDeepStartNarrow'](arg1);
}

export function UpdateDeepStartSelections(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateDeepStartSelections'](arg1, arg2, arg3);
}

export function UploadScreeningFiles(arg1, arg2) {
  return window['go']['main']['App']['UploadScreeningFiles'](arg1, arg2);
}
