// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFolder(arg1:string):Promise<main.Folder>;

export function DeletePaper(arg1:string):Promise<void>;

export function GetFolders():Promise<Array<main.Folder>>;

export function GetInitialState():Promise<main.InitialState>;

export function GetPapers(arg1:string):Promise<Array<main.Paper>>;

export function GetTranslations(arg1:string):Promise<Array<main.TranslationRecord>>;

export function Greet(arg1:string):Promise<string>;

export function ImportPapers(arg1:string,arg2:Array<main.SearchPaper>):Promise<Array<main.Paper>>;

export function SaveConfig(arg1:main.AppConfig):Promise<main.SaveConfigResult>;

export function SearchPapers(arg1:string,arg2:number):Promise<Array<main.SearchPaper>>;

export function TranslatePaperSection(arg1:string,arg2:string,arg3:string):Promise<main.TranslationRecord>;
