// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function DeletePaper(arg1) {
  return window['go']['main']['App']['DeletePaper'](arg1);
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function GetPapers(arg1) {
  return window['go']['main']['App']['GetPapers'](arg1);
}

export function GetTranslations(arg1) {
  return window['go']['main']['App']['GetTranslations'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportPapers(arg1, arg2) {
  return window['go']['main']['App']['ImportPapers'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SearchPapers(arg1, arg2) {
  return window['go']['main']['App']['SearchPapers'](arg1, arg2);
}

export function TranslatePaperSection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TranslatePaperSection'](arg1, arg2, arg3);
}
