// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzePapers(arg1:string):Promise<main.ScreeningDecisionNode>;

export function ApplyScreeningChoice(arg1:string,arg2:Array<string>):Promise<main.ScreeningDecisionNode>;

export function CancelScreening(arg1:string):Promise<void>;

export function CompleteScreening(arg1:string,arg2:string):Promise<Array<main.Paper>>;

export function CreateFolder(arg1:string):Promise<main.Folder>;

export function CreateScreeningSession(arg1:string):Promise<main.ScreeningSession>;

export function DeletePaper(arg1:string):Promise<void>;

export function EnhancedSearchPapers(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number,arg6:string):Promise<main.EnhancedSearchResult>;

export function ExtractPaperContent(arg1:string):Promise<main.ExtractProgress>;

export function GetDeepStartSession(arg1:string):Promise<main.DeepStartSessionDetail>;

export function GetExtractProgress(arg1:string):Promise<main.ExtractProgress>;

export function GetFolders():Promise<Array<main.Folder>>;

export function GetInitialState():Promise<main.InitialState>;

export function GetPapers(arg1:string):Promise<Array<main.Paper>>;

export function GetScreeningSession(arg1:string):Promise<main.ScreeningSessionDetail>;

export function GetSecretPrefill():Promise<main.ConfigSecretPrefill>;

export function GetSyncConflicts():Promise<Array<main.SyncConflict>>;

export function GetSyncProgress():Promise<main.SyncProgress>;

export function GetSyncRecords(arg1:number):Promise<Array<main.SyncRecord>>;

export function GetSyncStatus():Promise<main.SyncStatus>;

export function GetTranslations(arg1:string):Promise<Array<main.TranslationRecord>>;

export function Greet(arg1:string):Promise<string>;

export function ImportPapers(arg1:string,arg2:Array<main.SearchPaper>):Promise<Array<main.Paper>>;

export function ListDeepStartSessions():Promise<Array<main.DeepStartSessionSummary>>;

export function ListScreeningSessions():Promise<Array<main.ScreeningSession>>;

export function ReplyDeepStartSession(arg1:string,arg2:string):Promise<main.DeepStartSessionDetail>;

export function RerunDeepStartSearch(arg1:string,arg2:string):Promise<main.DeepStartSessionDetail>;

export function ResolveSyncConflict(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<main.SaveConfigResult>;

export function SearchPapers(arg1:string,arg2:number):Promise<Array<main.SearchPaper>>;

export function StartDeepStartSession(arg1:string,arg2:string):Promise<main.DeepStartSessionDetail>;

export function TranslatePaperSection(arg1:string,arg2:string,arg3:string):Promise<main.TranslationRecord>;

export function TriggerSync():Promise<main.SyncProgress>;

export function UpdateDeepStartSelections(arg1:string,arg2:Array<string>,arg3:string):Promise<main.DeepStartSessionDetail>;

export function UploadScreeningFiles(arg1:string,arg2:Array<string>):Promise<main.ScreeningSessionDetail>;
